version: "3.8"

services:
  mongo:
    image: mongo
    restart: always
    volumes:
      - ./data:/root/data
      - ./logs:/root/logs
      - ./mongod.conf:/etc/mongod.conf
      - /etc/letsencrypt/live/kelseywilliams.co/privkey.pem:/etc/privkey.pem:ro
      - /etc/letsencrypt/live/kelseywilliams.co/fullchain.pem:/etc/fullchain.pem:ro
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    entrypoint: ["mongod","--config","/etc/mongod.conf"]
    networks:
      - site
    ports:
      - "2999:2999"

networks:
  site:
    external: true
